"""updated nullables and added year row

Revision ID: eb2cfa7c7a83
Revises: 65ba7585b2ec
Create Date: 2021-03-04 12:13:21.624496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2cfa7c7a83'
down_revision = '65ba7585b2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('year', sa.Integer(), nullable=False))
    op.alter_column('trims', 'cylinders',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trims', 'doors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trims', 'fuel_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trims', 'fuel_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('trims', 'doors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trims', 'cylinders',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('models', 'year')
    # ### end Alembic commands ###
