"""created the broker deal picture table

Revision ID: 0b00838c84f4
Revises: 613290c305dc
Create Date: 2021-03-02 14:25:11.273043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b00838c84f4'
down_revision = '613290c305dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_deal_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('broker_deal_id', sa.Integer(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['broker_deal_id'], ['broker_deals.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_deal_pictures')
    # ### end Alembic commands ###
