"""added accepted to user inquiry table

Revision ID: a6c294e35941
Revises: ad065917f59f
Create Date: 2021-03-25 12:24:00.614603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c294e35941'
down_revision = 'ad065917f59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_inquiries', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_inquiries', 'accepted')
    # ### end Alembic commands ###
