"""updated user model

Revision ID: 5ee8c9ca7d6f
Revises: ffdc0a98111c
Create Date: 2021-03-02 12:36:15.041001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee8c9ca7d6f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('broker', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('dealer', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('header', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'name')
    op.drop_column('users', 'header')
    op.drop_column('users', 'dealer')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'city')
    op.drop_column('users', 'broker')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
