"""fixed relationships and broker reply

Revision ID: 0415e65a22ba
Revises: 13433b34b407
Create Date: 2021-03-02 13:27:53.004300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0415e65a22ba'
down_revision = '13433b34b407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_comment_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('reply', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_comment_id'], ['user_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_replies')
    # ### end Alembic commands ###
