"""created the broker deal note table

Revision ID: 613290c305dc
Revises: 1d7385e175a5
Create Date: 2021-03-02 14:21:40.833002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613290c305dc'
down_revision = '1d7385e175a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_deal_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('broker_deal_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['broker_deal_id'], ['broker_deals.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_deal_notes')
    # ### end Alembic commands ###
