"""fixed foreign keys and created broker reply table

Revision ID: 13433b34b407
Revises: 9de43b12ba2e
Create Date: 2021-03-02 13:15:38.433896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13433b34b407'
down_revision = '9de43b12ba2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_comments', 'users', ['broker_id'], ['id'])
    op.create_foreign_key(None, 'user_comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_comments', type_='foreignkey')
    op.drop_constraint(None, 'user_comments', type_='foreignkey')
    # ### end Alembic commands ###
