"""empty message

Revision ID: 57ac373078c5
Revises: 
Create Date: 2022-03-21 18:57:23.516879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ac373078c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('header', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('broker', sa.Boolean(), nullable=True),
    sa.Column('dealer', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('miles_yearly', sa.Integer(), nullable=False),
    sa.Column('money_factor', sa.Float(), nullable=False),
    sa.Column('residual', sa.Integer(), nullable=False),
    sa.Column('msrp', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('additional_fees', sa.Float(), nullable=False),
    sa.Column('payment', sa.Float(), nullable=False),
    sa.Column('active_month_year', sa.Date(), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    op.drop_table('users')
    # ### end Alembic commands ###
