"""empty message

Revision ID: 7ff8f7f0073c
Revises: f0d68c63103c
Create Date: 2022-03-22 10:24:53.589859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff8f7f0073c'
down_revision = 'f0d68c63103c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('trim', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'trim')
    # ### end Alembic commands ###
