"""empty message

Revision ID: f0d68c63103c
Revises: 57ac373078c5
Create Date: 2022-03-21 19:17:45.619333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d68c63103c'
down_revision = '57ac373078c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('miles', sa.Integer(), nullable=False))
    op.drop_column('deals', 'miles_yearly')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('miles_yearly', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('deals', 'miles')
    # ### end Alembic commands ###
